apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-data
  namespace: teamcity
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  resources:
    requests:
      storage: 20Gi
