apiVersion: v1
kind: Service
metadata:
  name: teamcity-service
  namespace: teamcity
spec:
  type: NodePort
  selector:
    app: teamcity-server
  ports:
  - port: 8111
    targetPort: 8111
    nodePort: 30111
