apiVersion: v1
kind: Pod
metadata:
  name: test-ed
spec:
  containers:
  - image: alpine:latest
    name: test-ed1
    command: ["/bin/sh","-c","sleep 3600;"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume

  - image: alpine:latest
    name: test-ed2
    command: ["/bin/sh","-c","sleep 3600;"]
    volumeMounts:
    - mountPath: /opt
      name: cache-volume    
  volumes:
  - name: cache-volume
    emptyDir: {}
