apiVersion: v1
kind: PersistentVolumeClaim          # 资源类型：pvc
metadata:
  name: nfs-pvc                   # PVC 的名字
spec:
  volumeMode: Filesystem        # 存储类型：文件系统
  accessModes:                 # 访问模式：ReadWriteOnce ReadWriteMany ReadOnlyMany
    - ReadWriteOnce             # ReadWriteOnce: 可被单节点读写
  storageClassName: slow        #
  resources:
    requests:
      storage: 5Gi            # 资源可以≤PV，否则会匹配不到 pv

