// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminUser = "admin_user"

// AdminUser 管理员表
type AdminUser struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键-管理员 id 表" json:"id"`                     // 主键-管理员 id 表
	Name       string    `gorm:"column:name;type:varchar(255);not null;index:idx_name,priority:1;comment:名字" json:"name"`               // 名字
	NickName   string    `gorm:"column:nick_name;type:varchar(255);not null;comment:昵称" json:"nick_name"`                               // 昵称
	Mobile     string    `gorm:"column:mobile;type:varchar(255);not null;uniqueIndex:idx_mobile,priority:1;comment:手机号码" json:"mobile"` // 手机号码
	LarkOpenID string    `gorm:"column:lark_open_id;type:varchar(255);not null;comment:用于飞书扫码登录" json:"lark_open_id"`                   // 用于飞书扫码登录
	Password   string    `gorm:"column:password;type:varchar(255);not null;comment:密码" json:"password"`                                 // 密码
	Status     int64     `gorm:"column:status;type:tinyint;not null;default:-1;comment:1:正常   -1: 禁用" json:"status"`                    // 1:正常   -1: 禁用
	CreateAt   time.Time `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt   time.Time `gorm:"column:update_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	CreateBy   int64     `gorm:"column:create_by;type:bigint;not null" json:"create_by"`
	UpdateBy   int64     `gorm:"column:update_by;type:bigint;not null;default:1" json:"update_by"`
	Sex        int64     `gorm:"column:sex;type:tinyint;not null;default:3;comment:性别   3: 其他  1: 男  2: 女" json:"sex"` // 性别   3: 其他  1: 男  2: 女
	IsDelete   int64     `gorm:"column:is_delete;type:tinyint;not null" json:"is_delete"`
}

// TableName AdminUser's table name
func (*AdminUser) TableName() string {
	return TableNameAdminUser
}
