// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAppUser = "app_user"

// AppUser 应用用户表
type AppUser struct {
	ID       int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:自增（无实际用途）" json:"id"`                                                     // 自增（无实际用途）
	UserID   int64     `gorm:"column:user_id;type:bigint;not null;uniqueIndex:uidx_user_appcode,priority:1;comment:全局用户id,user表主键" json:"user_id"`                  // 全局用户id,user表主键
	AppCode  int64     `gorm:"column:app_code;type:int;not null;uniqueIndex:uidx_user_appcode,priority:2;comment:1000=公众号,1001=小程序, 其他进扩展,固定值不能变更" json:"app_code"` // 1000=公众号,1001=小程序, 其他进扩展,固定值不能变更
	OpenID   string    `gorm:"column:open_id;type:varchar(128);not null;uniqueIndex:uidx_openId,priority:1;comment:当前存储微信应用的openid" json:"open_id"`                 // 当前存储微信应用的openid
	Status   int64     `gorm:"column:status;type:tinyint;not null;default:1;comment:默认1：正常-1：禁用" json:"status"`                                                     // 默认1：正常-1：禁用
	CreateAt time.Time `gorm:"column:create_at;type:datetime;not null" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;type:datetime;not null" json:"update_at"`
}

// TableName AppUser's table name
func (*AppUser) TableName() string {
	return TableNameAppUser
}
