// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCourseCatalog = "course_catalog"

// CourseCatalog 课程目录表
type CourseCatalog struct {
	ID       int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ParentID int64     `gorm:"column:parent_id;type:bigint;not null;default:-1;comment:父层级 id" json:"parent_id"` // 父层级 id
	Level    int64     `gorm:"column:level;type:int;not null;default:1" json:"level"`
	Name     string    `gorm:"column:name;type:varchar(255);not null" json:"name"`
	GoodID   int64     `gorm:"column:good_id;type:bigint;not null;index:idx_course,priority:1;comment:商品 id" json:"good_id"` // 商品 id
	Sort     int64     `gorm:"column:sort;type:bigint;not null" json:"sort"`
	UpdateAt time.Time `gorm:"column:update_at;type:datetime;not null" json:"update_at"`
	UpdateBy int64     `gorm:"column:update_by;type:bigint;not null" json:"update_by"`
}

// TableName CourseCatalog's table name
func (*CourseCatalog) TableName() string {
	return TableNameCourseCatalog
}
