// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCourseLesson = "course_lessons"

// CourseLesson 课程课时表
type CourseLesson struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	GoodsID     int64     `gorm:"column:goods_id;type:bigint;not null;index:idx_gid,priority:1" json:"goods_id"`
	CatalogID   int64     `gorm:"column:catalog_id;type:bigint;not null;index:idx_ct_id,priority:1" json:"catalog_id"`
	Name        string    `gorm:"column:name;type:varchar(255);not null;comment:课时名称" json:"name"`                    // 课时名称
	EnableTrial int64     `gorm:"column:enable_trial;type:tinyint;not null;comment:1:试听其他值表示非试听" json:"enable_trial"` // 1:试听其他值表示非试听
	Status      int64     `gorm:"column:status;type:tinyint;not null;comment:1：启用-1：禁用" json:"status"`                // 1：启用-1：禁用
	VideoKey    string    `gorm:"column:video_key;type:varchar(255);not null;comment:文件key" json:"video_key"`         // 文件key
	Detail      string    `gorm:"column:detail;type:text;not null;comment:课时详情" json:"detail"`                        // 课时详情
	Homework    string    `gorm:"column:homework;type:text;not null;comment:课后练习" json:"homework"`                    // 课后练习
	Sort        int64     `gorm:"column:sort;type:tinyint;not null" json:"sort"`
	UpdateAt    time.Time `gorm:"column:update_at;type:datetime;not null" json:"update_at"`
	UpdateBy    int64     `gorm:"column:update_by;type:bigint;not null" json:"update_by"`
}

// TableName CourseLesson's table name
func (*CourseLesson) TableName() string {
	return TableNameCourseLesson
}
