// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCourseGood = "course_goods"

// CourseGood 课程商品表
type CourseGood struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;type:varchar(255);not null;uniqueIndex:uidx_name,priority:1" json:"name"`
	CoverKey    string    `gorm:"column:cover_key;type:varchar(255);not null;comment:封面图key" json:"cover_key"` // 封面图key
	IntroKey    string    `gorm:"column:intro_key;type:varchar(255);not null;comment:详情图key" json:"intro_key"` // 详情图key
	Desc        string    `gorm:"column:desc;type:varchar(255);not null" json:"desc"`
	GoodsPrice  int64     `gorm:"column:goods_price;type:bigint;not null;comment:商品价格" json:"goods_price"`                             // 商品价格
	ServiceTime int64     `gorm:"column:service_time;type:tinyint;not null;comment:辅导服务时长 1：—个月 2：三个月 3：半年 4: 1年" json:"service_time"` // 辅导服务时长 1：—个月 2：三个月 3：半年 4: 1年
	SaleType    int64     `gorm:"column:sale_type;type:tinyint;not null;comment:1:免费 2：收费" json:"sale_type"`                           // 1:免费 2：收费
	Status      int64     `gorm:"column:status;type:tinyint;not null;default:-1;comment:-1：下架 1：上架" json:"status"`                     // -1：下架 1：上架
	CreateAt    time.Time `gorm:"column:create_at;type:datetime;not null" json:"create_at"`
	CreateBy    int64     `gorm:"column:create_by;type:bigint;not null" json:"create_by"`
	UpdateAt    time.Time `gorm:"column:update_at;type:datetime;not null" json:"update_at"`
	UpdateBy    int64     `gorm:"column:update_by;type:bigint;not null" json:"update_by"`
}

// TableName CourseGood's table name
func (*CourseGood) TableName() string {
	return TableNameCourseGood
}
