// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrderItem = "order_items"

// OrderItem 订单商品对象表
type OrderItem struct {
	ID        int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	OrderID   int64  `gorm:"column:order_id;type:bigint;not null;index:idx_oid,priority:1" json:"order_id"`
	UserID    int64  `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	GoodsID   int64  `gorm:"column:goods_id;type:bigint;not null;index:idx_gid,priority:1;comment:商品ID" json:"goods_id"` // 商品ID
	GoodsType int64  `gorm:"column:goods_type;type:tinyint;not null;default:1;comment:1:课程商品" json:"goods_type"`         // 1:课程商品
	Quantity  int64  `gorm:"column:quantity;type:int;not null;default:1;comment:商品数量" json:"quantity"`                   // 商品数量
	GoodsSnap string `gorm:"column:goods_snap;type:text;not null;comment:商品快照信息" json:"goods_snap"`                      // 商品快照信息
}

// TableName OrderItem's table name
func (*OrderItem) TableName() string {
	return TableNameOrderItem
}
