// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrder = "orders"

// Order 订单表
type Order struct {
	ID                  int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	OrderNo             string `gorm:"column:order_no;type:char(18);not null;uniqueIndex:idx_odno,priority:1;comment:订单号" json:"order_no"`                  // 订单号
	UserID              int64  `gorm:"column:user_id;type:bigint;not null;index:idx_uid,priority:1;comment:用户ID" json:"user_id"`                            // 用户ID
	Status              int64  `gorm:"column:status;type:tinyint;not null;default:1;comment:-1：已取消,1：待付 2：已付（待发货）" json:"status"`                           // -1：已取消,1：待付 2：已付（待发货）
	OrderSource         int64  `gorm:"column:order_source;type:tinyint;not null;index:idx_osrc,priority:1;comment:1：户下单 2：管理后台 3：系统赠送" json:"order_source"` // 1：户下单 2：管理后台 3：系统赠送
	OrderAmount         int64  `gorm:"column:order_amount;type:bigint;not null;comment:订单金额=支付金额,单位:分" json:"order_amount"`                                 // 订单金额=支付金额,单位:分
	OrderOriginAmount   int64  `gorm:"column:order_origin_amount;type:bigint;not null;comment:订单金额-商品原价,单位分" json:"order_origin_amount"`                    // 订单金额-商品原价,单位分
	PaymentAmount       int64  `gorm:"column:payment_amount;type:bigint;not null;comment:支付金额-实际支付金额,单位分°" json:"payment_amount"`                           // 支付金额-实际支付金额,单位分°
	TradeNo             string `gorm:"column:trade_no;type:varchar(255);not null;index:idx_trade_no,priority:1;comment:交易号" json:"trade_no"`                // 交易号
	InnerTradeNo        string `gorm:"column:inner_trade_no;type:varchar(255);not null;comment:内部支付订单号" json:"inner_trade_no"`                              // 内部支付订单号
	OrderDesc           string `gorm:"column:order_desc;type:mediumtext;not null" json:"order_desc"`
	PaymentAt           int64  `gorm:"column:payment_at;type:bigint;not null;index:idx_pay_at,priority:1;comment:订单付时间,毫秒时间戳" json:"payment_at"`      // 订单付时间,毫秒时间戳
	UserRemark          string `gorm:"column:user_remark;type:varchar(255);not null;comment:用户备注" json:"user_remark"`                                 // 用户备注
	ReceiverConfirmAt   int64  `gorm:"column:receiver_confirm_at;type:bigint;comment:确认收货时间" json:"receiver_confirm_at"`                              // 确认收货时间
	ReceiverConfirmType int64  `gorm:"column:receiver_confirm_type;type:tinyint;comment:确认收货式1：用户确认收货 99:发货10天自动收货" json:"receiver_confirm_type"`     // 确认收货式1：用户确认收货 99:发货10天自动收货
	RefundAmount        int64  `gorm:"column:refund_amount;type:bigint;not null;comment:订单退款金额" json:"refund_amount"`                                 // 订单退款金额
	RefundAt            int64  `gorm:"column:refund_at;type:bigint;comment:退款时间,毫秒时间戳" json:"refund_at"`                                              // 退款时间,毫秒时间戳
	CancelAt            int64  `gorm:"column:cancel_at;type:bigint;comment:取消时间,毫秒时间戳" json:"cancel_at"`                                              // 取消时间,毫秒时间戳
	CancelType          int64  `gorm:"column:cancel_type;type:tinyint;comment:1：用户取消 2：客服取消 3：超时取消" json:"cancel_type"`                               // 1：用户取消 2：客服取消 3：超时取消
	CancelBy            int64  `gorm:"column:cancel_by;type:bigint;comment:取消人ID,跟据取消类型判断是用户还是客服。-1为系统超时取消" json:"cancel_by"`                         // 取消人ID,跟据取消类型判断是用户还是客服。-1为系统超时取消
	CancelReason        string `gorm:"column:cancel_reason;type:varchar(255);comment:取消理由" json:"cancel_reason"`                                      // 取消理由
	CreateAt            int64  `gorm:"column:create_at;type:bigint;not null;index:idx_create,priority:1;comment:订单创建时间,毫秒时间戳" json:"create_at"`       // 订单创建时间,毫秒时间戳
	CreateBy            int64  `gorm:"column:create_by;type:bigint;not null;comment:订单创建人 ID,根据 order_source 判断是用户,还是客服 ID, -1 为系统" json:"create_by"` // 订单创建人 ID,根据 order_source 判断是用户,还是客服 ID, -1 为系统
	TransferAt          int64  `gorm:"column:transfer_at;type:bigint;not null;comment:转交时间" json:"transfer_at"`                                       // 转交时间
	TransferBy          int64  `gorm:"column:transfer_by;type:bigint;not null;comment:转交人" json:"transfer_by"`                                        // 转交人
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
