// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePermission = "permission"

// Permission 权限清单表
type Permission struct {
	ID       int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Code     string    `gorm:"column:code;type:varchar(255);not null;uniqueIndex:idx_code,priority:1;comment:权限编码" json:"code"`                 // 权限编码
	Type     int64     `gorm:"column:type;type:tinyint;not null;comment:1:菜单 2:操作" json:"type"`                                                 // 1:菜单 2:操作
	Name     string    `gorm:"column:name;type:varchar(255);not null;index:idx_name,priority:1;comment:权限名称" json:"name"`                       // 权限名称
	PagePath string    `gorm:"column:page_path;type:varchar(255);not null;comment:菜单路径" json:"page_path"`                                       // 菜单路径
	ParentID int64     `gorm:"column:parent_id;type:bigint;not null;index:idx_parent_id,priority:1;default:-1;comment:父级权限ID" json:"parent_id"` // 父级权限ID
	Status   int64     `gorm:"column:status;type:tinyint;not null;uniqueIndex:idx_code,priority:2;comment:1:正常-1:禁用" json:"status"`             // 1:正常-1:禁用
	Sort     int64     `gorm:"column:sort;type:int;not null;default:1" json:"sort"`
	Desc     string    `gorm:"column:desc;type:varchar(255);not null;comment:权限描述" json:"desc"` // 权限描述
	CreateAt time.Time `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;type:datetime;not null" json:"update_at"`
	UpdateBy int64     `gorm:"column:update_by;type:bigint;not null" json:"update_by"`
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
