// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRolePermission = "role_permission"

// RolePermission 角色权限表
type RolePermission struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	RoleID       int64     `gorm:"column:role_id;type:bigint;not null;index:idx_role_id,priority:1;comment:角色ID" json:"role_id"` // 角色ID
	PermissionID int64     `gorm:"column:permission_id;type:bigint;not null;comment:权限ID" json:"permission_id"`                  // 权限ID
	CreateAt     time.Time `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt     time.Time `gorm:"column:update_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	CreateBy     int64     `gorm:"column:create_by;type:bigint;not null" json:"create_by"`
	UpdateBy     int64     `gorm:"column:update_by;type:bigint;not null" json:"update_by"`
}

// TableName RolePermission's table name
func (*RolePermission) TableName() string {
	return TableNameRolePermission
}
