// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRole = "roles"

// Role 角色表
type Role struct {
	ID       int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name     string    `gorm:"column:name;type:varchar(255);not null;uniqueIndex:uidx_name,priority:1;comment:角色名" json:"name"` // 角色名
	Desc     string    `gorm:"column:desc;type:varchar(255);not null;comment:角色描述" json:"desc"`                                 // 角色描述
	Status   int64     `gorm:"column:status;type:tinyint;not null;comment:1:正常-1：禁用" json:"status"`                             // 1:正常-1：禁用
	CreateAt time.Time `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	CreateBy int64     `gorm:"column:create_by;type:bigint;not null" json:"create_by"`
	UpdateBy int64     `gorm:"column:update_by;type:bigint;not null" json:"update_by"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
