// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSmsTemplate = "sms_template"

// SmsTemplate 短信模板表
type SmsTemplate struct {
	ID             int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SceneCode      string    `gorm:"column:scene_code;type:varchar(128);not null;uniqueIndex:uidx_scene,priority:1;comment:场景编码, 有意义的英文字符串" json:"scene_code"` // 场景编码, 有意义的英文字符串
	SignName       string    `gorm:"column:sign_name;type:varchar(255);not null;comment:短信签名, 需要去短信平台审核" json:"sign_name"`                                     // 短信签名, 需要去短信平台审核
	PlatformTmplID int64     `gorm:"column:platform_tmpl_id;type:int;not null;comment:第三方短信平台的模版ID" json:"platform_tmpl_id"`                                   // 第三方短信平台的模版ID
	TmplStr        string    `gorm:"column:tmpl_str;type:varchar(255);not null;comment:短信模板内容, 该字符串内容可先设置, 后续开放管理后台修改" json:"tmpl_str"`                        // 短信模板内容, 该字符串内容可先设置, 后续开放管理后台修改
	Status         int64     `gorm:"column:status;type:tinyint;not null;default:1;comment:默认1：正常-1：禁用" json:"status"`                                          // 默认1：正常-1：禁用
	CreateAt       time.Time `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt       time.Time `gorm:"column:update_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	AdminUserID    int64     `gorm:"column:admin_user_id;type:bigint;not null;comment:管理后台admin_user_id" json:"admin_user_id"` // 管理后台admin_user_id
	Platform       string    `gorm:"column:platform;type:char(8);not null;comment:tencer" json:"platform"`                     // tencer
}

// TableName SmsTemplate's table name
func (*SmsTemplate) TableName() string {
	return TableNameSmsTemplate
}
