// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserCourseGood = "user_course_goods"

// UserCourseGood 用户购买的课程列表
type UserCourseGood struct {
	ID                int64 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID            int64 `gorm:"column:user_id;type:bigint;not null;index:idx_uid,priority:1;comment:用户ID" json:"user_id"`                               // 用户ID
	OrderID           int64 `gorm:"column:order_id;type:bigint;not null;comment:订单ID" json:"order_id"`                                                      // 订单ID
	GoodsID           int64 `gorm:"column:goods_id;type:bigint;not null;index:idx_cid,priority:1;comment:商品ID" json:"goods_id"`                             // 商品ID
	GoodsType         int64 `gorm:"column:goods_type;type:tinyint;not null;comment:1.课程商品" json:"goods_type"`                                               // 1.课程商品
	BuyTime           int64 `gorm:"column:buy_time;type:bigint;not null;comment:购买时间" json:"buy_time"`                                                      // 购买时间
	ServiceExpireTime int64 `gorm:"column:service_expire_time;type:bigint;not null;index:idx_se_ex_t,priority:1;comment:服务到期时间" json:"service_expire_time"` // 服务到期时间
}

// TableName UserCourseGood's table name
func (*UserCourseGood) TableName() string {
	return TableNameUserCourseGood
}
