// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User 用户主表
type User struct {
	ID          int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:全局user_id" json:"id"` // 全局user_id
	NickName    string    `gorm:"column:nick_name;type:varchar(64);not null;index:idx_name,priority:1" json:"nick_name"`
	Sex         int64     `gorm:"column:sex;type:tinyint;not null;comment:默认e其他,1：男2：女" json:"sex"`                                       // 默认e其他,1：男2：女
	Password    string    `gorm:"column:password;type:varchar(64);not null;comment:64长度,全局唯一—个密码,不支持呢称登录,支持微信登录和手机号密码登录" json:"password"` // 64长度,全局唯一—个密码,不支持呢称登录,支持微信登录和手机号密码登录
	Status      int64     `gorm:"column:status;type:tinyint;not null;default:1;comment:默认1：正常-1：禁用" json:"status"`                        // 默认1：正常-1：禁用
	IconKey     string    `gorm:"column:icon_key;type:varchar(255);not null;comment:长度固定32,云存储key uuid" json:"icon_key"`                  // 长度固定32,云存储key uuid
	CreateAt    time.Time `gorm:"column:create_at;type:datetime;not null" json:"create_at"`
	LastLoginAt time.Time `gorm:"column:last_login_at;type:datetime" json:"last_login_at"`
	UpdateAt    time.Time `gorm:"column:update_at;type:datetime;not null" json:"update_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
