// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWechatUser = "wechat_user"

// WechatUser 微信用户表
type WechatUser struct {
	ID       int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID,自增（无实际用途）" json:"id"`                             // 主键ID,自增（无实际用途）
	UserID   int64     `gorm:"column:user_id;type:bigint;not null;uniqueIndex:uidx_user,priority:1;comment:全局用户id,user表主键" json:"user_id"`       // 全局用户id,user表主键
	UnionID  string    `gorm:"column:union_id;type:varchar(128);not null;uniqueIndex:KEYuidx_union,priority:1;comment:微信唯一用户ID" json:"union_id"` // 微信唯一用户ID
	NickName string    `gorm:"column:nick_name;type:varchar(128);not null;comment:微信呢称" json:"nick_name"`                                        // 微信呢称
	IconURL  string    `gorm:"column:icon_url;type:varchar(255);not null;comment:128长度微信头像" json:"icon_url"`                                     // 128长度微信头像
	CreateAt time.Time `gorm:"column:create_at;type:datetime;not null" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;type:datetime;not null" json:"update_at"`
}

// TableName WechatUser's table name
func (*WechatUser) TableName() string {
	return TableNameWechatUser
}
