[legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
background-color='rgb(35,109,133)'
background-transparency-percent=56
bold-color='rgb(197,66,66)'
bold-color-same-as-fg=false
foreground-color='rgb(147,234,103)'
highlight-background-color='rgb(35,109,133)'
highlight-colors-set=true
highlight-foreground-color='rgb(191,57,57)'
use-theme-colors=false
use-theme-transparency=false
use-transparent-background=true
