// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newCourseLesson(db *gorm.DB, opts ...gen.DOOption) courseLesson {
	_courseLesson := courseLesson{}

	_courseLesson.courseLessonDo.UseDB(db, opts...)
	_courseLesson.courseLessonDo.UseModel(&model.CourseLesson{})

	tableName := _courseLesson.courseLessonDo.TableName()
	_courseLesson.ALL = field.NewAsterisk(tableName)
	_courseLesson.ID = field.NewInt64(tableName, "id")
	_courseLesson.GoodsID = field.NewInt64(tableName, "goods_id")
	_courseLesson.CatalogID = field.NewInt64(tableName, "catalog_id")
	_courseLesson.Name = field.NewString(tableName, "name")
	_courseLesson.EnableTrial = field.NewInt64(tableName, "enable_trial")
	_courseLesson.Status = field.NewInt64(tableName, "status")
	_courseLesson.VideoKey = field.NewString(tableName, "video_key")
	_courseLesson.Detail = field.NewString(tableName, "detail")
	_courseLesson.Homework = field.NewString(tableName, "homework")
	_courseLesson.Sort = field.NewInt64(tableName, "sort")
	_courseLesson.UpdateAt = field.NewTime(tableName, "update_at")
	_courseLesson.UpdateBy = field.NewInt64(tableName, "update_by")

	_courseLesson.fillFieldMap()

	return _courseLesson
}

// courseLesson 课程课时表
type courseLesson struct {
	courseLessonDo

	ALL         field.Asterisk
	ID          field.Int64
	GoodsID     field.Int64
	CatalogID   field.Int64
	Name        field.String // 课时名称
	EnableTrial field.Int64  // 1:试听其他值表示非试听
	Status      field.Int64  // 1：启用-1：禁用
	VideoKey    field.String // 文件key
	Detail      field.String // 课时详情
	Homework    field.String // 课后练习
	Sort        field.Int64
	UpdateAt    field.Time
	UpdateBy    field.Int64

	fieldMap map[string]field.Expr
}

func (c courseLesson) Table(newTableName string) *courseLesson {
	c.courseLessonDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c courseLesson) As(alias string) *courseLesson {
	c.courseLessonDo.DO = *(c.courseLessonDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *courseLesson) updateTableName(table string) *courseLesson {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.GoodsID = field.NewInt64(table, "goods_id")
	c.CatalogID = field.NewInt64(table, "catalog_id")
	c.Name = field.NewString(table, "name")
	c.EnableTrial = field.NewInt64(table, "enable_trial")
	c.Status = field.NewInt64(table, "status")
	c.VideoKey = field.NewString(table, "video_key")
	c.Detail = field.NewString(table, "detail")
	c.Homework = field.NewString(table, "homework")
	c.Sort = field.NewInt64(table, "sort")
	c.UpdateAt = field.NewTime(table, "update_at")
	c.UpdateBy = field.NewInt64(table, "update_by")

	c.fillFieldMap()

	return c
}

func (c *courseLesson) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *courseLesson) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 12)
	c.fieldMap["id"] = c.ID
	c.fieldMap["goods_id"] = c.GoodsID
	c.fieldMap["catalog_id"] = c.CatalogID
	c.fieldMap["name"] = c.Name
	c.fieldMap["enable_trial"] = c.EnableTrial
	c.fieldMap["status"] = c.Status
	c.fieldMap["video_key"] = c.VideoKey
	c.fieldMap["detail"] = c.Detail
	c.fieldMap["homework"] = c.Homework
	c.fieldMap["sort"] = c.Sort
	c.fieldMap["update_at"] = c.UpdateAt
	c.fieldMap["update_by"] = c.UpdateBy
}

func (c courseLesson) clone(db *gorm.DB) courseLesson {
	c.courseLessonDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c courseLesson) replaceDB(db *gorm.DB) courseLesson {
	c.courseLessonDo.ReplaceDB(db)
	return c
}

type courseLessonDo struct{ gen.DO }

type ICourseLessonDo interface {
	gen.SubQuery
	Debug() ICourseLessonDo
	WithContext(ctx context.Context) ICourseLessonDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICourseLessonDo
	WriteDB() ICourseLessonDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICourseLessonDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICourseLessonDo
	Not(conds ...gen.Condition) ICourseLessonDo
	Or(conds ...gen.Condition) ICourseLessonDo
	Select(conds ...field.Expr) ICourseLessonDo
	Where(conds ...gen.Condition) ICourseLessonDo
	Order(conds ...field.Expr) ICourseLessonDo
	Distinct(cols ...field.Expr) ICourseLessonDo
	Omit(cols ...field.Expr) ICourseLessonDo
	Join(table schema.Tabler, on ...field.Expr) ICourseLessonDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICourseLessonDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICourseLessonDo
	Group(cols ...field.Expr) ICourseLessonDo
	Having(conds ...gen.Condition) ICourseLessonDo
	Limit(limit int) ICourseLessonDo
	Offset(offset int) ICourseLessonDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICourseLessonDo
	Unscoped() ICourseLessonDo
	Create(values ...*model.CourseLesson) error
	CreateInBatches(values []*model.CourseLesson, batchSize int) error
	Save(values ...*model.CourseLesson) error
	First() (*model.CourseLesson, error)
	Take() (*model.CourseLesson, error)
	Last() (*model.CourseLesson, error)
	Find() ([]*model.CourseLesson, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CourseLesson, err error)
	FindInBatches(result *[]*model.CourseLesson, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CourseLesson) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICourseLessonDo
	Assign(attrs ...field.AssignExpr) ICourseLessonDo
	Joins(fields ...field.RelationField) ICourseLessonDo
	Preload(fields ...field.RelationField) ICourseLessonDo
	FirstOrInit() (*model.CourseLesson, error)
	FirstOrCreate() (*model.CourseLesson, error)
	FindByPage(offset int, limit int) (result []*model.CourseLesson, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICourseLessonDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c courseLessonDo) Debug() ICourseLessonDo {
	return c.withDO(c.DO.Debug())
}

func (c courseLessonDo) WithContext(ctx context.Context) ICourseLessonDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c courseLessonDo) ReadDB() ICourseLessonDo {
	return c.Clauses(dbresolver.Read)
}

func (c courseLessonDo) WriteDB() ICourseLessonDo {
	return c.Clauses(dbresolver.Write)
}

func (c courseLessonDo) Session(config *gorm.Session) ICourseLessonDo {
	return c.withDO(c.DO.Session(config))
}

func (c courseLessonDo) Clauses(conds ...clause.Expression) ICourseLessonDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c courseLessonDo) Returning(value interface{}, columns ...string) ICourseLessonDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c courseLessonDo) Not(conds ...gen.Condition) ICourseLessonDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c courseLessonDo) Or(conds ...gen.Condition) ICourseLessonDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c courseLessonDo) Select(conds ...field.Expr) ICourseLessonDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c courseLessonDo) Where(conds ...gen.Condition) ICourseLessonDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c courseLessonDo) Order(conds ...field.Expr) ICourseLessonDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c courseLessonDo) Distinct(cols ...field.Expr) ICourseLessonDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c courseLessonDo) Omit(cols ...field.Expr) ICourseLessonDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c courseLessonDo) Join(table schema.Tabler, on ...field.Expr) ICourseLessonDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c courseLessonDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICourseLessonDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c courseLessonDo) RightJoin(table schema.Tabler, on ...field.Expr) ICourseLessonDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c courseLessonDo) Group(cols ...field.Expr) ICourseLessonDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c courseLessonDo) Having(conds ...gen.Condition) ICourseLessonDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c courseLessonDo) Limit(limit int) ICourseLessonDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c courseLessonDo) Offset(offset int) ICourseLessonDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c courseLessonDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICourseLessonDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c courseLessonDo) Unscoped() ICourseLessonDo {
	return c.withDO(c.DO.Unscoped())
}

func (c courseLessonDo) Create(values ...*model.CourseLesson) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c courseLessonDo) CreateInBatches(values []*model.CourseLesson, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c courseLessonDo) Save(values ...*model.CourseLesson) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c courseLessonDo) First() (*model.CourseLesson, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseLesson), nil
	}
}

func (c courseLessonDo) Take() (*model.CourseLesson, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseLesson), nil
	}
}

func (c courseLessonDo) Last() (*model.CourseLesson, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseLesson), nil
	}
}

func (c courseLessonDo) Find() ([]*model.CourseLesson, error) {
	result, err := c.DO.Find()
	return result.([]*model.CourseLesson), err
}

func (c courseLessonDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CourseLesson, err error) {
	buf := make([]*model.CourseLesson, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c courseLessonDo) FindInBatches(result *[]*model.CourseLesson, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c courseLessonDo) Attrs(attrs ...field.AssignExpr) ICourseLessonDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c courseLessonDo) Assign(attrs ...field.AssignExpr) ICourseLessonDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c courseLessonDo) Joins(fields ...field.RelationField) ICourseLessonDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c courseLessonDo) Preload(fields ...field.RelationField) ICourseLessonDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c courseLessonDo) FirstOrInit() (*model.CourseLesson, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseLesson), nil
	}
}

func (c courseLessonDo) FirstOrCreate() (*model.CourseLesson, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CourseLesson), nil
	}
}

func (c courseLessonDo) FindByPage(offset int, limit int) (result []*model.CourseLesson, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c courseLessonDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c courseLessonDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c courseLessonDo) Delete(models ...*model.CourseLesson) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *courseLessonDo) withDO(do gen.Dao) *courseLessonDo {
	c.DO = *do.(*gen.DO)
	return c
}
