// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newMobileUser(db *gorm.DB, opts ...gen.DOOption) mobileUser {
	_mobileUser := mobileUser{}

	_mobileUser.mobileUserDo.UseDB(db, opts...)
	_mobileUser.mobileUserDo.UseModel(&model.MobileUser{})

	tableName := _mobileUser.mobileUserDo.TableName()
	_mobileUser.ALL = field.NewAsterisk(tableName)
	_mobileUser.ID = field.NewInt64(tableName, "id")
	_mobileUser.UserID = field.NewInt64(tableName, "user_id")
	_mobileUser.MobileAes = field.NewString(tableName, "mobile_aes")
	_mobileUser.MobileSha256 = field.NewString(tableName, "mobile_sha256")
	_mobileUser.CreateAt = field.NewTime(tableName, "create_at")
	_mobileUser.UpdateAt = field.NewTime(tableName, "update_at")

	_mobileUser.fillFieldMap()

	return _mobileUser
}

// mobileUser 手机用户表
type mobileUser struct {
	mobileUserDo

	ALL          field.Asterisk
	ID           field.Int64  // 自增,更换手机号码硬删除
	UserID       field.Int64  // user表主键
	MobileAes    field.String // aes加密后的手机号,用于解密回显
	MobileSha256 field.String // sha256加密后的手机号,用于全值搜索
	CreateAt     field.Time
	UpdateAt     field.Time

	fieldMap map[string]field.Expr
}

func (m mobileUser) Table(newTableName string) *mobileUser {
	m.mobileUserDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mobileUser) As(alias string) *mobileUser {
	m.mobileUserDo.DO = *(m.mobileUserDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mobileUser) updateTableName(table string) *mobileUser {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.UserID = field.NewInt64(table, "user_id")
	m.MobileAes = field.NewString(table, "mobile_aes")
	m.MobileSha256 = field.NewString(table, "mobile_sha256")
	m.CreateAt = field.NewTime(table, "create_at")
	m.UpdateAt = field.NewTime(table, "update_at")

	m.fillFieldMap()

	return m
}

func (m *mobileUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mobileUser) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 6)
	m.fieldMap["id"] = m.ID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["mobile_aes"] = m.MobileAes
	m.fieldMap["mobile_sha256"] = m.MobileSha256
	m.fieldMap["create_at"] = m.CreateAt
	m.fieldMap["update_at"] = m.UpdateAt
}

func (m mobileUser) clone(db *gorm.DB) mobileUser {
	m.mobileUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mobileUser) replaceDB(db *gorm.DB) mobileUser {
	m.mobileUserDo.ReplaceDB(db)
	return m
}

type mobileUserDo struct{ gen.DO }

type IMobileUserDo interface {
	gen.SubQuery
	Debug() IMobileUserDo
	WithContext(ctx context.Context) IMobileUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMobileUserDo
	WriteDB() IMobileUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMobileUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMobileUserDo
	Not(conds ...gen.Condition) IMobileUserDo
	Or(conds ...gen.Condition) IMobileUserDo
	Select(conds ...field.Expr) IMobileUserDo
	Where(conds ...gen.Condition) IMobileUserDo
	Order(conds ...field.Expr) IMobileUserDo
	Distinct(cols ...field.Expr) IMobileUserDo
	Omit(cols ...field.Expr) IMobileUserDo
	Join(table schema.Tabler, on ...field.Expr) IMobileUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMobileUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMobileUserDo
	Group(cols ...field.Expr) IMobileUserDo
	Having(conds ...gen.Condition) IMobileUserDo
	Limit(limit int) IMobileUserDo
	Offset(offset int) IMobileUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMobileUserDo
	Unscoped() IMobileUserDo
	Create(values ...*model.MobileUser) error
	CreateInBatches(values []*model.MobileUser, batchSize int) error
	Save(values ...*model.MobileUser) error
	First() (*model.MobileUser, error)
	Take() (*model.MobileUser, error)
	Last() (*model.MobileUser, error)
	Find() ([]*model.MobileUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MobileUser, err error)
	FindInBatches(result *[]*model.MobileUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MobileUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMobileUserDo
	Assign(attrs ...field.AssignExpr) IMobileUserDo
	Joins(fields ...field.RelationField) IMobileUserDo
	Preload(fields ...field.RelationField) IMobileUserDo
	FirstOrInit() (*model.MobileUser, error)
	FirstOrCreate() (*model.MobileUser, error)
	FindByPage(offset int, limit int) (result []*model.MobileUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMobileUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mobileUserDo) Debug() IMobileUserDo {
	return m.withDO(m.DO.Debug())
}

func (m mobileUserDo) WithContext(ctx context.Context) IMobileUserDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mobileUserDo) ReadDB() IMobileUserDo {
	return m.Clauses(dbresolver.Read)
}

func (m mobileUserDo) WriteDB() IMobileUserDo {
	return m.Clauses(dbresolver.Write)
}

func (m mobileUserDo) Session(config *gorm.Session) IMobileUserDo {
	return m.withDO(m.DO.Session(config))
}

func (m mobileUserDo) Clauses(conds ...clause.Expression) IMobileUserDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mobileUserDo) Returning(value interface{}, columns ...string) IMobileUserDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mobileUserDo) Not(conds ...gen.Condition) IMobileUserDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mobileUserDo) Or(conds ...gen.Condition) IMobileUserDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mobileUserDo) Select(conds ...field.Expr) IMobileUserDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mobileUserDo) Where(conds ...gen.Condition) IMobileUserDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mobileUserDo) Order(conds ...field.Expr) IMobileUserDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mobileUserDo) Distinct(cols ...field.Expr) IMobileUserDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mobileUserDo) Omit(cols ...field.Expr) IMobileUserDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mobileUserDo) Join(table schema.Tabler, on ...field.Expr) IMobileUserDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mobileUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMobileUserDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mobileUserDo) RightJoin(table schema.Tabler, on ...field.Expr) IMobileUserDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mobileUserDo) Group(cols ...field.Expr) IMobileUserDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mobileUserDo) Having(conds ...gen.Condition) IMobileUserDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mobileUserDo) Limit(limit int) IMobileUserDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mobileUserDo) Offset(offset int) IMobileUserDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mobileUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMobileUserDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mobileUserDo) Unscoped() IMobileUserDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mobileUserDo) Create(values ...*model.MobileUser) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mobileUserDo) CreateInBatches(values []*model.MobileUser, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mobileUserDo) Save(values ...*model.MobileUser) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mobileUserDo) First() (*model.MobileUser, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MobileUser), nil
	}
}

func (m mobileUserDo) Take() (*model.MobileUser, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MobileUser), nil
	}
}

func (m mobileUserDo) Last() (*model.MobileUser, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MobileUser), nil
	}
}

func (m mobileUserDo) Find() ([]*model.MobileUser, error) {
	result, err := m.DO.Find()
	return result.([]*model.MobileUser), err
}

func (m mobileUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MobileUser, err error) {
	buf := make([]*model.MobileUser, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mobileUserDo) FindInBatches(result *[]*model.MobileUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mobileUserDo) Attrs(attrs ...field.AssignExpr) IMobileUserDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mobileUserDo) Assign(attrs ...field.AssignExpr) IMobileUserDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mobileUserDo) Joins(fields ...field.RelationField) IMobileUserDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mobileUserDo) Preload(fields ...field.RelationField) IMobileUserDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mobileUserDo) FirstOrInit() (*model.MobileUser, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MobileUser), nil
	}
}

func (m mobileUserDo) FirstOrCreate() (*model.MobileUser, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MobileUser), nil
	}
}

func (m mobileUserDo) FindByPage(offset int, limit int) (result []*model.MobileUser, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mobileUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mobileUserDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mobileUserDo) Delete(models ...*model.MobileUser) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mobileUserDo) withDO(do gen.Dao) *mobileUserDo {
	m.DO = *do.(*gen.DO)
	return m
}
