// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mall/adaptor/repo/model"
)

func newResourceUploadFile(db *gorm.DB, opts ...gen.DOOption) resourceUploadFile {
	_resourceUploadFile := resourceUploadFile{}

	_resourceUploadFile.resourceUploadFileDo.UseDB(db, opts...)
	_resourceUploadFile.resourceUploadFileDo.UseModel(&model.ResourceUploadFile{})

	tableName := _resourceUploadFile.resourceUploadFileDo.TableName()
	_resourceUploadFile.ALL = field.NewAsterisk(tableName)
	_resourceUploadFile.ID = field.NewInt64(tableName, "id")
	_resourceUploadFile.Scene = field.NewString(tableName, "scene")
	_resourceUploadFile.FileKey = field.NewString(tableName, "file_key")
	_resourceUploadFile.UserID = field.NewInt64(tableName, "user_id")
	_resourceUploadFile.UserType = field.NewInt64(tableName, "user_type")
	_resourceUploadFile.FileType = field.NewString(tableName, "file_type")
	_resourceUploadFile.FileSize = field.NewInt64(tableName, "file_size")
	_resourceUploadFile.FileName = field.NewString(tableName, "file_name")
	_resourceUploadFile.UploadClientIP = field.NewString(tableName, "upload_client_ip")
	_resourceUploadFile.CreateAt = field.NewTime(tableName, "create_at")

	_resourceUploadFile.fillFieldMap()

	return _resourceUploadFile
}

// resourceUploadFile 资源文件上传表
type resourceUploadFile struct {
	resourceUploadFileDo

	ALL            field.Asterisk
	ID             field.Int64  // 主键 ID
	Scene          field.String // 业务场景编码
	FileKey        field.String // 文件key, 文件路径
	UserID         field.Int64  // 用户id
	UserType       field.Int64  // 用户类型
	FileType       field.String // 文件类型对应文件后缀
	FileSize       field.Int64  // 文件大小对应字节数
	FileName       field.String // 文件名
	UploadClientIP field.String // 文件上传端的ip
	CreateAt       field.Time   // 文件创建时间=上传时间

	fieldMap map[string]field.Expr
}

func (r resourceUploadFile) Table(newTableName string) *resourceUploadFile {
	r.resourceUploadFileDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resourceUploadFile) As(alias string) *resourceUploadFile {
	r.resourceUploadFileDo.DO = *(r.resourceUploadFileDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resourceUploadFile) updateTableName(table string) *resourceUploadFile {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.Scene = field.NewString(table, "scene")
	r.FileKey = field.NewString(table, "file_key")
	r.UserID = field.NewInt64(table, "user_id")
	r.UserType = field.NewInt64(table, "user_type")
	r.FileType = field.NewString(table, "file_type")
	r.FileSize = field.NewInt64(table, "file_size")
	r.FileName = field.NewString(table, "file_name")
	r.UploadClientIP = field.NewString(table, "upload_client_ip")
	r.CreateAt = field.NewTime(table, "create_at")

	r.fillFieldMap()

	return r
}

func (r *resourceUploadFile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resourceUploadFile) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 10)
	r.fieldMap["id"] = r.ID
	r.fieldMap["scene"] = r.Scene
	r.fieldMap["file_key"] = r.FileKey
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["user_type"] = r.UserType
	r.fieldMap["file_type"] = r.FileType
	r.fieldMap["file_size"] = r.FileSize
	r.fieldMap["file_name"] = r.FileName
	r.fieldMap["upload_client_ip"] = r.UploadClientIP
	r.fieldMap["create_at"] = r.CreateAt
}

func (r resourceUploadFile) clone(db *gorm.DB) resourceUploadFile {
	r.resourceUploadFileDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resourceUploadFile) replaceDB(db *gorm.DB) resourceUploadFile {
	r.resourceUploadFileDo.ReplaceDB(db)
	return r
}

type resourceUploadFileDo struct{ gen.DO }

type IResourceUploadFileDo interface {
	gen.SubQuery
	Debug() IResourceUploadFileDo
	WithContext(ctx context.Context) IResourceUploadFileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IResourceUploadFileDo
	WriteDB() IResourceUploadFileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IResourceUploadFileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IResourceUploadFileDo
	Not(conds ...gen.Condition) IResourceUploadFileDo
	Or(conds ...gen.Condition) IResourceUploadFileDo
	Select(conds ...field.Expr) IResourceUploadFileDo
	Where(conds ...gen.Condition) IResourceUploadFileDo
	Order(conds ...field.Expr) IResourceUploadFileDo
	Distinct(cols ...field.Expr) IResourceUploadFileDo
	Omit(cols ...field.Expr) IResourceUploadFileDo
	Join(table schema.Tabler, on ...field.Expr) IResourceUploadFileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IResourceUploadFileDo
	RightJoin(table schema.Tabler, on ...field.Expr) IResourceUploadFileDo
	Group(cols ...field.Expr) IResourceUploadFileDo
	Having(conds ...gen.Condition) IResourceUploadFileDo
	Limit(limit int) IResourceUploadFileDo
	Offset(offset int) IResourceUploadFileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceUploadFileDo
	Unscoped() IResourceUploadFileDo
	Create(values ...*model.ResourceUploadFile) error
	CreateInBatches(values []*model.ResourceUploadFile, batchSize int) error
	Save(values ...*model.ResourceUploadFile) error
	First() (*model.ResourceUploadFile, error)
	Take() (*model.ResourceUploadFile, error)
	Last() (*model.ResourceUploadFile, error)
	Find() ([]*model.ResourceUploadFile, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResourceUploadFile, err error)
	FindInBatches(result *[]*model.ResourceUploadFile, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ResourceUploadFile) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IResourceUploadFileDo
	Assign(attrs ...field.AssignExpr) IResourceUploadFileDo
	Joins(fields ...field.RelationField) IResourceUploadFileDo
	Preload(fields ...field.RelationField) IResourceUploadFileDo
	FirstOrInit() (*model.ResourceUploadFile, error)
	FirstOrCreate() (*model.ResourceUploadFile, error)
	FindByPage(offset int, limit int) (result []*model.ResourceUploadFile, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IResourceUploadFileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r resourceUploadFileDo) Debug() IResourceUploadFileDo {
	return r.withDO(r.DO.Debug())
}

func (r resourceUploadFileDo) WithContext(ctx context.Context) IResourceUploadFileDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resourceUploadFileDo) ReadDB() IResourceUploadFileDo {
	return r.Clauses(dbresolver.Read)
}

func (r resourceUploadFileDo) WriteDB() IResourceUploadFileDo {
	return r.Clauses(dbresolver.Write)
}

func (r resourceUploadFileDo) Session(config *gorm.Session) IResourceUploadFileDo {
	return r.withDO(r.DO.Session(config))
}

func (r resourceUploadFileDo) Clauses(conds ...clause.Expression) IResourceUploadFileDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resourceUploadFileDo) Returning(value interface{}, columns ...string) IResourceUploadFileDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resourceUploadFileDo) Not(conds ...gen.Condition) IResourceUploadFileDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resourceUploadFileDo) Or(conds ...gen.Condition) IResourceUploadFileDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resourceUploadFileDo) Select(conds ...field.Expr) IResourceUploadFileDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resourceUploadFileDo) Where(conds ...gen.Condition) IResourceUploadFileDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resourceUploadFileDo) Order(conds ...field.Expr) IResourceUploadFileDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resourceUploadFileDo) Distinct(cols ...field.Expr) IResourceUploadFileDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resourceUploadFileDo) Omit(cols ...field.Expr) IResourceUploadFileDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resourceUploadFileDo) Join(table schema.Tabler, on ...field.Expr) IResourceUploadFileDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resourceUploadFileDo) LeftJoin(table schema.Tabler, on ...field.Expr) IResourceUploadFileDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resourceUploadFileDo) RightJoin(table schema.Tabler, on ...field.Expr) IResourceUploadFileDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resourceUploadFileDo) Group(cols ...field.Expr) IResourceUploadFileDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resourceUploadFileDo) Having(conds ...gen.Condition) IResourceUploadFileDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resourceUploadFileDo) Limit(limit int) IResourceUploadFileDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resourceUploadFileDo) Offset(offset int) IResourceUploadFileDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resourceUploadFileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceUploadFileDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resourceUploadFileDo) Unscoped() IResourceUploadFileDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resourceUploadFileDo) Create(values ...*model.ResourceUploadFile) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resourceUploadFileDo) CreateInBatches(values []*model.ResourceUploadFile, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resourceUploadFileDo) Save(values ...*model.ResourceUploadFile) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resourceUploadFileDo) First() (*model.ResourceUploadFile, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceUploadFile), nil
	}
}

func (r resourceUploadFileDo) Take() (*model.ResourceUploadFile, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceUploadFile), nil
	}
}

func (r resourceUploadFileDo) Last() (*model.ResourceUploadFile, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceUploadFile), nil
	}
}

func (r resourceUploadFileDo) Find() ([]*model.ResourceUploadFile, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResourceUploadFile), err
}

func (r resourceUploadFileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResourceUploadFile, err error) {
	buf := make([]*model.ResourceUploadFile, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resourceUploadFileDo) FindInBatches(result *[]*model.ResourceUploadFile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resourceUploadFileDo) Attrs(attrs ...field.AssignExpr) IResourceUploadFileDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resourceUploadFileDo) Assign(attrs ...field.AssignExpr) IResourceUploadFileDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resourceUploadFileDo) Joins(fields ...field.RelationField) IResourceUploadFileDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resourceUploadFileDo) Preload(fields ...field.RelationField) IResourceUploadFileDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resourceUploadFileDo) FirstOrInit() (*model.ResourceUploadFile, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceUploadFile), nil
	}
}

func (r resourceUploadFileDo) FirstOrCreate() (*model.ResourceUploadFile, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceUploadFile), nil
	}
}

func (r resourceUploadFileDo) FindByPage(offset int, limit int) (result []*model.ResourceUploadFile, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resourceUploadFileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resourceUploadFileDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resourceUploadFileDo) Delete(models ...*model.ResourceUploadFile) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resourceUploadFileDo) withDO(do gen.Dao) *resourceUploadFileDo {
	r.DO = *do.(*gen.DO)
	return r
}
